using AiNotetakerApp.Models;
using AiNotetakerApp.Data;
using CommunityToolkit.Mvvm.ComponentModel;
using CommunityToolkit.Mvvm.Input;
using System.Collections.ObjectModel;
using System.Threading.Tasks;

namespace AiNotetakerApp.ViewModels
{
    public partial class MainViewModel: ObservableObject
    {
        private readonly DatabaseService _databaseService;

        // ObservableCollection automatically updates the UI when items are added or removed
        [ObservableProperty]
        private ObservableCollection<Meeting> _meetings;

        [ObservableProperty]
        private bool _isBusy;

        // Constructor Injection: The app automatically provides the DatabaseService here
        public MainViewModel(DatabaseService databaseService)
        {
            _databaseService = databaseService;
            _meetings = new ObservableCollection<Meeting>();
        }

        // The [RelayCommand} attribute automatically turns this method into a command
        // that you button can bind to in the XAML (e.g., Command="{Binding LoadMeetingsCommand}")
        [RelayCommand]
        public async Task LoadMeetingsAsync()
        {
            if (_isBusy) return;

            try
            {
                IsBusy = true;

                // Fetch from database
                var meetingsFromDb = await _databaseService.GetMeetingAsync();

                // Clear and reload the observable collection
                Meetings.Clear();
                foreach (var meeting in meetingsFromDb)
                {
                    Meetings.Add(meeting);
                }
            }
            finally { IsBusy = false; };
        }

        [RelayCommand]
        public async Task SaveMeetingsAsync()
        {
            // For testing the UI before we build the recording logic
            var newMeeting = new Meeting
            {
                Title = "Test Sync Meeting",
                StartTime = System.DateTime.Now.AddHours(-1),
                EndTime = System.DateTime.Now,
                AiSummary = "This is a test summary generated by the Viewmodel."
            };

            await _databaseService.SaveMeetingAsync(newMeeting);

            // Reload the list to show the new Item
            await LoadMeetingsAsync();
        }
    }
}